verion=1.0

[main]
name.en = "Renew KeyStore Certificate"
name.fr = "Renouveller le certificat du porte-cl√©"

    [main.configuration]
        [main.configuration.install_keystore]
        ask.en = "Renew"
        ask.fr = "Renouveller"
        type = "button"

        
